### ISSUE TITLE
SCORM Cloud  - 1.2 errors

### ISSUE THREAD

**Issue by jasonbutler** [pipwerks/scorm-api-wrapper#16]
After testing on SCORM Cloud the Example 1.2 version has a fatal error. Details of Parser errors below:

An item element was found that references a resource/submanifest with the identifier 'SCO_Resource_01' that does not exist.

The external metadata referenced at /courses/463303XQOD/SCORM1.2versione0daf84d-da83-4e4e-a3ca-36bd988ed7a6/0/SCORM 1.2 version\imsmetadata.xml could not be opened. The specific exception was: java.io.FileNotFoundException: /courses/463303XQOD/SCORM1.2versione0daf84d-da83-4e4e-a3ca-36bd988ed7a6/0/SCORM 1.2 version (Is a directory)

The 2004 version works fine though with completion status of passed once the form is submitted.

**Comment by pipwerks** [comment]
If you're using a manifest I included in one of the examples on my website (which are not in this GitHub repo), I will admit some of those manifests are not the greatest, and need some cleanup. You can eliminate the errant metadata link in the 1.2 example, or you can get a nice new manifest from http://www.scormsoft.com/scorm/cam/manifestFiles
