### ISSUE TITLE
General Argument Error (201) with scorm.set("cmi.progress_measure", "0.4");

### ISSUE THREAD

**Issue by BaptisteBriel** [pipwerks/scorm-api-wrapper#17]
Hello,

I have an issue with the scorm API wrapper when I want to update the course's percentage.
I think I'm currently using the 2004 version.

```javascript
scorm.set("cmi.progress_measure", "0,4");
scorm.save();
```

When running on CrossKnowledge's test platform, I've got this error in the bottom console (not the DevTools one!)

[2015-05-06 15:04:38] LMSSetValue("cmi.progress_measure", "0.4")
[2015-05-06 15:04:38] ERROR: (201) Invalid argument error
[2015-05-06 15:04:38] LMSCommit("")

Do you have any ideas why? Maybe I'm not using the 2004 version so "cmi.progress_measure" is not available? (http://scorm.com/scorm-explained/technical-scorm/run-time/run-time-reference/)

Thank you for your time.

**Comment by pipwerks** [comment]
Hello

Your sample code uses a comma `0,4` where a decimal point is required `0.4`. This aligns with the _Invalid Argument_ error. Does changing it to a decimal point fix the issue?

**Comment by BaptisteBriel** [comment]
Hello,

I think it's because I'm not using the 2004 version.
By default, the version is "1.2" :

```javascript
console.log(scorm);

scorm.version = "2004";
console.log(scorm.version);

var progress = scorm.get("cmi.progress_measure");
	
scorm.set("cmi.progress_measure", "0.4");
scorm.save();
```

Still doesn't work. Looks like I can't even get the current progress measure.
I have this error in the DevTools console :

![](https://cloud.githubusercontent.com/assets/2464663/7511103/cee7095e-f4a2-11e4-80af-25caca2aef2c.png)

I'm using the latest API wrapper here. Maybe I'm just doing something wrong.
https://github.com/pipwerks/scorm-api-wrapper/blob/master/src/JavaScript/SCORM_API_wrapper.js

It's quite strange because the progress of the course goes up to 1% even if there's the error.

Thank you!

**Comment by BaptisteBriel** [comment]
My bad, I had to define the version before the init.
Now I don't have any errors with this code:

```javascript
function init(){
    scorm.version = "2004";
    var connected = scorm.init();
    
    scorm.set("cmi.progress_measure", "0.4");
    scorm.save();
}

window.onload = init;
```

It's running on version 2004, but the progress bar is still at 0%. I don't really get why.

**Comment by BaptisteBriel** [comment]
I figured out why it isn't working: looks like it can't be used with browserify.
Sorry for the inconvenience.
