### ISSUE TITLE
error accessing win.top.opener

### ISSUE THREAD

**Issue by jheinstein** [pipwerks/scorm-api-wrapper#19]
I was getting an error on IE11 (but not Chrome or Firefox) that win.top.opener is undefined.

This is happening on line 119 :

if(!API && win.top.opener && win.top.opener.document) {

This is fixed by adding an additional check for win.top

if(!API **&& win.top** && win.top.opener && win.top.opener.document) {

**Comment by pipwerks** [comment]
`window.top` is a standard property, it should always be available. Curious that it's not working in IE11.

I have updated the src to check, just in case. Thanks
