### ISSUE TITLE
Package game into SCORM

### ISSUE THREAD

**Issue by black-lotus** [pipwerks/scorm-api-wrapper#25]
Hi, first of all thank you for making this awesome api wrapper.
I just wanna ask how you guys success to upload your package to SCORM engine, 
I have never been succeed when tried to upload my game to it, by the way i am using moodle.

My package game is .zip file

Any help would be appreciated
Thanks

**Comment by razorfish79** [comment]
This is not an issue of the SCORM wrapper. You need to have some more than just a Zip file. Beside the wrapper you need to make a SCORM package of your files. For this purpose I use the RELOAD Editor but there are also other tools available. The package contains a manifest file which is needed.

**Comment by black-lotus** [comment]
hi @razorfish79 i just doesn't know how to deal with scorm since i always getting an error even i zip my game.
i saw an example on youtube but it's to complicated since i have to create several xml file. 
is "reload editor" create manifest scorm to us ?
thank you in advance

**Comment by razorfish79** [comment]
You can find the Reload Editor as linked below. It is well documented. The Reload Editor does the creation of all needed files for you. You just need to adjust some settings depending on your SCORM-Version and your content.

Reload Editor Software: http://www.reload.ac.uk/editor.html
Reload Editor Documents http://www.reload.ac.uk/guide.html

**Comment by black-lotus** [comment]
@razorfish79 nice, thank you very much 💯
