### ISSUE TITLE
Version 2004 Errors

### ISSUE THREAD

**Issue by bknill** [pipwerks/scorm-api-wrapper#27]
HI, 

I'm playing with this in Moodle and have got the course installed as a SCORM Package and it's running. It seems to connect to the API

`SCORM.API.find: API found. Version: 2004` 

Then there is this warning

request.js:2 Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.

And no connections work after that. 

```
connection.initialize called.
SCORM_API_wrapper.js:837 SCORM.API.find: API found. Version: 2004
SCORM_API_wrapper.js:837 API: [object Object]
SCORM_API_wrapper.js:837 SCORM.data.get('cmi.completion_status')  value: unknown
SCORM_API_wrapper.js:837 SCORM.data.set('cmi.completion_status')  value: incomplete
**request.js:2 Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.**
SCORM_API_wrapper.js:837 SCORM.data.get('cmi.core.lesson_status') failed. 
Error code: 401
Error info: Undefinited Data Model
SCORM_API_wrapper.js:837 SCORM.data.get('cmi.core.lesson_status')  value: 
SCORM_API_wrapper.js:837 SCORM.data.get('cmi.core.student_name') failed. 
Error code: 401
Error info: Undefinited Data Model
SCORM_API_wrapper.js:837 SCORM.data.get('cmi.core.student_name')  value: 
```

I'm using a local version of the latest Moodle for testing. Should I be using SCORM 2004 packages or SCORM 1.2 ?

**Comment by bknill** [comment]
Rolled back to 1.2 and it's working

**Comment by pipwerks** [comment]
If you'd like to use SCORM 2004 in your course, you need to use the corresponding CMI fields. Your code has SCORM 1.2 CMI fields (eg cmi.core.student_name) and not SCORM 2004 CMI fields (eg cmi.learner_name). That's why it failed. Update your CMI fields appropriately and the SCORM 2004 code will work. See http://scorm.com/scorm-explained/technical-scorm/run-time/run-time-reference for a list of fields.

**Comment by bknill** [comment]
Ah cool OK thanks. I think I was following out of date instructions.

**Comment by moloko** [comment]
Also be aware that Moodle no longer officially supports SCORM 2004. I would test SCORM 2004 content on SCORM Cloud instead.

**Comment by bknill** [comment]
Oh really? OK is that a consistent standard across the LMS's? I've got it working in Moodle with 2004. Would it be less buggy to just use the older standard? 

I've got TinCan working with the LRS in SCORM Cloud, I'll have a play with running SCORM packages - it's just faster testing on my local. 

Thanks

**Comment by pipwerks** [comment]
SCORM 2004 is more difficult for LMS vendors to implement, so SCORM 1.2 is widely viewed as a safer choice.
