### ISSUE TITLE
Calling Quit Method Shouldn't Force 'cmi.exit' to 'normal'

### ISSUE THREAD

**Issue by thejamespower** [pipwerks/scorm-api-wrapper#29]
The connection.terminate() method overrides developer set cmi.exit if completion_status is complete etc. While this makes some sense, for many use cases we need to specifically KEEP suspend_data after completing the course. Is there anyway of doing this with this wrapper?

**Comment by pipwerks** [comment]
If you set a value for cmi.exit yourself, the wrapper will not override your choice; the wrapper only sets a value if you have not already done it yourself.

You can also disable the auto-handling of the cmi.exit as described here: https://pipwerks.com/2008/05/18/scorm-api-wrapper-116/
