### ISSUE TITLE
Scorm loads slowly

### ISSUE THREAD

**Issue by VuHoang1991** [pipwerks/scorm-api-wrapper#32]
Hi @pipwerks I'm using your scorm wrapper for my course and I realise that scorm object loads really slow on LMS (my case is: CanvasLMS). Any idea about that? 
I don't know what is inside scorm that make the course runs slowly.  I've tried to upload my course into a server and it running really nice. 

Thanks!

**Comment by pipwerks** [comment]
Sorry, no idea. I suggest you check with the CanvasLMS folks, it's probably an issue with their service.
