### ISSUE TITLE
SCORM 2004 4th Edition

### ISSUE THREAD

**Issue by boxgames1** [pipwerks/scorm-api-wrapper#34]
Hi,

I am having problems with this edition of SCORM 2004. The 3rd edition is working perfectly.

However, with this one, It looks like not getting well the API.

Here's the log screenshot running the course on Scorm Cloud.

![seleccion_004](https://user-images.githubusercontent.com/11459130/28969708-fdabf24a-7925-11e7-817d-bdc270940a69.png)

**Comment by pipwerks** [comment]
The wrapper is agnostic to editions of SCORM 2004. It treats them all the same. The differences between 3rd and 4th editions are minor, and did not require any modifications to the wrapper. The log entry you posted does not point to any issues with the wrapper. I suggest double-checking the LMS settings and ensuring you're actually using SCORM 2004 4th edition.
