### ISSUE TITLE
LearningApps embedded 

### ISSUE THREAD

**Issue by githubwyllie** [pipwerks/scorm-api-wrapper#46]
Hey guys!

I am looking forward to use some scrom packages on a learning-system. I embedded an existing scrom package from www.learningapps.org they use out of the box this api-wrapper. 

But when I load the following page a few errors appears: 

https://www.mein-klassenzimmer.de/test/

SCORM.connection.terminate aborted: Connection already terminated. SCORM_API_wrapper.js:913:32
connection.initialize called. SCORM_API_wrapper.js:913:32
SCORM.API.find: Error finding API. 
Find attempts: 0. 
Find attempt limit: 500 SCORM_API_wrapper.js:913:32
API.get failed: Can't find the API! SCORM_API_wrapper.js:913:32
SCORM.connection.initialize failed: API is null.

Have you got any idea?

**Comment by pipwerks** [comment]
Hi @githubwyllie 

SCORM courses must be launched from a learning management system that provides the SCORM API as a JavaScript object in `window`. Also, a SCORM course requires the connection to be established once (usually upon course launch) then maintained over the life of the course. You can't connect then disconnect on every page.

This thread talks about it a little bit.
https://stackoverflow.com/questions/36269434/scorm-course-in-iframe-cant-find-api

Good luck

**Comment by githubwyllie** [comment]
@pipwerks Thanks!
