### ISSUE TITLE
Licensing information missing

### ISSUE THREAD

**Issue by Aratch** [pipwerks/scorm-api-wrapper#48]
I'm potentially interested in using your wrapper (or a fork/reimplementation) in an open source project, but I'm wary of the legal ramifications with regards to licensing (or rather, the lack thereof). While the headers provide ample documentation as to where the code comes from, it still bugs me that a mature package such as this one lacks a licence.

As a matter of fact, during my research I've seen several npm packages that may or may not be derived from your wrapper (but are, more likely than not, related to the original ADL code). Rustici's stance on open source software makes me wary, as well.

I'm aware of [this MIT-licensed project on github](https://github.com/szenadam/scorm-api-wrapper) which explicitly cites this library as an inspiration/prior art (which is a good thing imo).

Seeing as this project is pretty old and you don't have much free time, would you still consider taking a closer look and, if possible, add a license.md file?

**Comment by moloko** [comment]
Licencing information is in the README https://github.com/pipwerks/scorm-api-wrapper/blob/82e455b4032ee08febf64d2fa2bf1aacaebaa446/readme.md?plain=1#L4-L5

**Comment by Aratch** [comment]
Shoot, I'm blind. Closing this issue for being a non-issue then.

**Comment by pipwerks** [comment]
The license is also in the source JS, line 11
https://github.com/pipwerks/scorm-api-wrapper/blob/master/src/JavaScript/SCORM_API_wrapper.js#L11
