### ISSUE TITLE
Track scorm progress and need inquiry regarding lms and lrs

### ISSUE THREAD

**Issue by Mustufask** [pipwerks/scorm-api-wrapper#50]
pls can u help me, i have a query regarding scorm package

I'm reaching out with a query regarding your expertise with SCORM (Sharable Content Object Reference Model). Specifically, we have a SCORM zip file and are interested in tracking logs when this file is played. Could you kindly provide guidance on how to retrieve these logs programmatically?

Additionally, we are curious about the possibility of creating our own Learning Record Store (LRS) using ReactJS. Is it feasible to implement an LRS using this technology stack? If so, could you outline the steps or methods involved in integrating it with our application?

Your insights and expertise would be greatly appreciated. Looking forward to your guidance on these matters and how can i implement it with ur scorm-api-wrapper

Best regards,

Mustufa shaikh

**Comment by pipwerks** [comment]
Sorry, that's well beyond the scope of this project/repo. This wrapper is meant to be used within a SCORM package, not on the LMS side. Handling the LMS functionality is much more complicated.

**Comment by Mustufask** [comment]
can i track progress of my scorm file without an lms? because i already have a scorm file and want to use ur wrapper

**Comment by pipwerks** [comment]
Try https://github.com/jcputney/scorm-again

**Comment by Mustufask** [comment]
Sir can u pls help me to integrate scorm-again with my scorm package, bcz there's no proper implementation in forums of this library.

here's my code:
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Scorm Test</title>
    <script
      src="https://code.jquery.com/jquery-3.3.1.min.js"
      integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
      crossorigin="anonymous"
    ></script>
  </head>

  <body>
    <script
      type="text/javascript"
      src="./node_modules/scorm-again/src/Scorm12API.js"
    ></script>

    <script>
      function save() {
        console.log(window, "window");
      }
    </script>
    <iframe
      src="./story.html"
      width="550"
      height="450"
      frameborder="0"
    ></iframe>
    <button onclick="save()">Save</button>
  </body>
</html>

**Comment by Mustufask** [comment]
@pipwerks  sir if i want to use ur wrapper within my package so is there any possibility.
here's my zip file: https://github.com/Mustufask/Scorm-again

**Comment by pipwerks** [comment]
If you are using Articulate to create a course, my wrapper is unrelated to your needs. Good luck.
